### ISSUE TITLE
error: Error Undefined variable in expression: ....

### ISSUE THREAD

**Issue by myperx** [MrEliasen/Supremacy-Framework#14]
This is the server-side log:

`_m = createMarker [format["arms%1%2", _pos select 0, _pos select 1], _pos];
_m>
16:53:16   Error position: <_pos select 0, _pos select 1], _pos];
_m>
16:53:16   Error Undefined variable in expression: _pos
16:53:16 File supremacy_server\server\initShops.sqf, line 73
16:53:16 Error in expression <

_m = createMarker [format["arms%1%2", _pos select 0, _pos select 1], _pos];
_m>
16:53:16   Error position: <_pos select 0, _pos select 1], _pos];
_m>
16:53:16   Error Undefined variable in expression: _pos
16:53:16 File supremacy_server\server\initShops.sqf, line 73
16:53:16 Error in expression <able _x);
deleteVehicle (nearestObject [_y, "Land_Research_house_V1_F"]);
{ dele>
16:53:16   Error position: <_y, "Land_Research_house_V1_F"]);
{ dele>
16:53:16   Error Undefined variable in expression: _y
16:53:16 File supremacy_server\server\initShops.sqf, line 82
16:53:16 Error in expression <able _x);
deleteVehicle (nearestObject [_y, "Land_Research_house_V1_F"]);
{ dele>`

**Comment by MrEliasen** [comment]
Looks like the config (shop_air_vehicle_npc_list) contain npc names for npcs which are no longer in the map. Make sure you update the list when you add/remove any of them.

**Comment by MrEliasen** [comment]
I will push an update today with fixes to Altis and other bits.

**Comment by MrEliasen** [comment]
Update pushed. Please download the latest version and try again. :)
